/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
 * Generated on: 16-Dec-2020 20:36:24
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure  : Lattice Autoregressive Moving-Average (ARMA)
 * Lattice Length    : 10
 * Ladder Length     : 11
 * Stable            : Yes
 * Linear Phase      : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "arm_math.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int KL = 10;
const float32_t K[10] = {
    -0.9921748042,   0.9934774041,  -0.9927621484,   0.9912924767,  -0.9886029959,
     0.9833919406,   -0.971529007,   0.9334369898,  -0.7498345375,   0.2604082227
};
const int VL = 11;
const float32_t V[11] = {
  7.078336495e-08,3.847409857e-07,8.994861673e-07,1.225021151e-06,1.086153361e-06,
  6.572908546e-07, 2.75235152e-07, 7.86436587e-08,1.456547238e-08, 1.60725977e-09,
  8.614364777e-11
};
